# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x02\x61i\"8\n\x10\x41nonymizeRequest\x12\x10\n\x08raw_text\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\",\n\x11\x41nonymizeResponse\x12\x17\n\x0f\x61nonymized_text\x18\x01 \x01(\t\"X\n\x14StartWorkflowRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x17\n\x0f\x61nonymized_text\x18\x02 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x03 \x01(\t\"\xcc\x01\n\rWorkflowEvent\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0bicd10_codes\x18\x03 \x03(\t\x12\x18\n\x10\x63onfidence_score\x18\x04 \x01(\x02\x12\x12\n\npayer_type\x18\x05 \x01(\t\x12\x15\n\rquality_score\x18\x06 \x01(\x02\x12\x12\n\nstate_json\x18\x07 \x01(\t\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x13\n\x0bretry_count\x18\t \x01(\x05\"\xcf\x01\n\x10\x45xportPdfRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\npayer_type\x18\x03 \x01(\t\x12\x15\n\rquality_score\x18\x04 \x01(\x02\x12\x12\n\npatient_id\x18\x05 \x01(\t\x12\x13\n\x0b\x66ields_json\x18\x06 \x01(\t\x12$\n\x1ctemplate_file_content_base64\x18\x07 \x01(\t\x12\x1c\n\x14template_fields_json\x18\x08 \x01(\t\"&\n\x11\x45xportPdfResponse\x12\x11\n\tpdf_bytes\x18\x01 \x01(\x0c\";\n\x12\x45xtractTextRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\nfile_bytes\x18\x02 \x01(\x0c\"-\n\x13\x45xtractTextResponse\x12\x16\n\x0e\x65xtracted_text\x18\x01 \x01(\t2\x83\x02\n\tAiService\x12<\n\rAnonymizeText\x12\x14.ai.AnonymizeRequest\x1a\x15.ai.AnonymizeResponse\x12>\n\rStartWorkflow\x12\x18.ai.StartWorkflowRequest\x1a\x11.ai.WorkflowEvent0\x01\x12\x38\n\tExportPdf\x12\x14.ai.ExportPdfRequest\x1a\x15.ai.ExportPdfResponse\x12>\n\x0b\x45xtractText\x12\x16.ai.ExtractTextRequest\x1a\x17.ai.ExtractTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANONYMIZEREQUEST']._serialized_start=24
  _globals['_ANONYMIZEREQUEST']._serialized_end=80
  _globals['_ANONYMIZERESPONSE']._serialized_start=82
  _globals['_ANONYMIZERESPONSE']._serialized_end=126
  _globals['_STARTWORKFLOWREQUEST']._serialized_start=128
  _globals['_STARTWORKFLOWREQUEST']._serialized_end=216
  _globals['_WORKFLOWEVENT']._serialized_start=219
  _globals['_WORKFLOWEVENT']._serialized_end=423
  _globals['_EXPORTPDFREQUEST']._serialized_start=426
  _globals['_EXPORTPDFREQUEST']._serialized_end=633
  _globals['_EXPORTPDFRESPONSE']._serialized_start=635
  _globals['_EXPORTPDFRESPONSE']._serialized_end=673
  _globals['_EXTRACTTEXTREQUEST']._serialized_start=675
  _globals['_EXTRACTTEXTREQUEST']._serialized_end=734
  _globals['_EXTRACTTEXTRESPONSE']._serialized_start=736
  _globals['_EXTRACTTEXTRESPONSE']._serialized_end=781
  _globals['_AISERVICE']._serialized_start=784
  _globals['_AISERVICE']._serialized_end=1043
# @@protoc_insertion_point(module_scope)
