# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub:
    """Service to handle clinical text anonymization and Prior Authorization workflows.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnonymizeText = channel.unary_unary(
                '/ai.AiService/AnonymizeText',
                request_serializer=ai__service__pb2.AnonymizeRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AnonymizeResponse.FromString,
                _registered_method=True)
        self.StartWorkflow = channel.unary_stream(
                '/ai.AiService/StartWorkflow',
                request_serializer=ai__service__pb2.StartWorkflowRequest.SerializeToString,
                response_deserializer=ai__service__pb2.WorkflowEvent.FromString,
                _registered_method=True)
        self.ExportPdf = channel.unary_unary(
                '/ai.AiService/ExportPdf',
                request_serializer=ai__service__pb2.ExportPdfRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ExportPdfResponse.FromString,
                _registered_method=True)
        self.ExtractText = channel.unary_unary(
                '/ai.AiService/ExtractText',
                request_serializer=ai__service__pb2.ExtractTextRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ExtractTextResponse.FromString,
                _registered_method=True)


class AiServiceServicer:
    """Service to handle clinical text anonymization and Prior Authorization workflows.
    """

    def AnonymizeText(self, request, context):
        """Filters PHI (Protected Health Information) from clinical text before LLM consumption.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWorkflow(self, request, context):
        """Executes the LangGraph prior authorization workflow, streaming node events back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportPdf(self, request, context):
        """Generates and overlays PDF report for the workflow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractText(self, request, context):
        """Extracts text from uploaded files (PDF, DOCX, TXT, Images)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnonymizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnonymizeText,
                    request_deserializer=ai__service__pb2.AnonymizeRequest.FromString,
                    response_serializer=ai__service__pb2.AnonymizeResponse.SerializeToString,
            ),
            'StartWorkflow': grpc.unary_stream_rpc_method_handler(
                    servicer.StartWorkflow,
                    request_deserializer=ai__service__pb2.StartWorkflowRequest.FromString,
                    response_serializer=ai__service__pb2.WorkflowEvent.SerializeToString,
            ),
            'ExportPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportPdf,
                    request_deserializer=ai__service__pb2.ExportPdfRequest.FromString,
                    response_serializer=ai__service__pb2.ExportPdfResponse.SerializeToString,
            ),
            'ExtractText': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractText,
                    request_deserializer=ai__service__pb2.ExtractTextRequest.FromString,
                    response_serializer=ai__service__pb2.ExtractTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService:
    """Service to handle clinical text anonymization and Prior Authorization workflows.
    """

    @staticmethod
    def AnonymizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/AnonymizeText',
            ai__service__pb2.AnonymizeRequest.SerializeToString,
            ai__service__pb2.AnonymizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AiService/StartWorkflow',
            ai__service__pb2.StartWorkflowRequest.SerializeToString,
            ai__service__pb2.WorkflowEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/ExportPdf',
            ai__service__pb2.ExportPdfRequest.SerializeToString,
            ai__service__pb2.ExportPdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/ExtractText',
            ai__service__pb2.ExtractTextRequest.SerializeToString,
            ai__service__pb2.ExtractTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
