FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code and build Next.js application
COPY . .
RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production

# Run in production start mode
CMD ["npm", "run", "start"]
